from tkinter import *

def version_window():
    root = Tk()
    root.title('Konwerter kwartalny - przegląd uaktualnień wersji')
    scrollbar = Scrollbar(root)
    scrollbar.pack(side=RIGHT, fill=Y)
    textbox = Text(root)
    textbox.pack()

    textbox.insert(END, " * v0.8\n")
    textbox.insert(END, "     - dodana konwersja tygodniowa\n")
    textbox.insert(END, "     - zmiany wizualne\n\n\n\n")
    textbox.insert(END, " * v0.7\n")
    textbox.insert(END, "     - optymalizacja kodu skryptu dziennego (ogromny wzrost wydajności)\n")
    textbox.insert(END, "     - naprawiony skrypt OPEN_INT z wyświetlaniem rolowań\n")
    textbox.insert(END, "     - zmienione indeksowanie OPEN_INT\n\n\n\n")
    textbox.insert(END, " * v0.6\n")
    textbox.insert(END, "     - zmiana skryptu decyzyjnego\n")
    textbox.insert(END, "     - nowa walidacja danych\n")
    textbox.insert(END, "     - dodany progress bar\n")
    textbox.insert(END, "     - dodany licznik postępy\n")
    textbox.insert(END, "     - optymalizacja kodu źródłowego\n")
    textbox.insert(END, "     - integracja kodu źródłowego z konwerterem rolowań\n")
    textbox.insert(END, "     - usunięcie zbędnych druków w terminalu\n")
    textbox.insert(END, "     - zmiana rozmieszczenia UI\n\n\n\n")
    textbox.insert(END, " * v0.5\n")
    textbox.insert(END, "     - dodany gotowy skrypt do konwersji miesięcznej\n")
    textbox.insert(END, "     - naprawiony błąd związany z brakiem mozliwości konwersji po\n")
    textbox.insert(END, "       jednokrotnym uzyciu programu\n")
    textbox.insert(END, "     - poprawki błędów wizualnych\n\n\n\n")
    textbox.insert(END, " * v0.4\n")
    textbox.insert(END, "     - dodana funkcjonalność skryptu decyzyjnego pod konwersje miesięczną\n")
    textbox.insert(END, "     - naprawiony błąd skryptu kwartalnego (ucinanie najnowszej\n")
    textbox.insert(END, "       świecy trwającego kontraktu)\n\n\n\n")
    textbox.insert(END, " * v0.3.1\n")
    textbox.insert(END, "     - poprawiony zapis nazwy pliku po konwersji\n")
    textbox.insert(END, "     - poprawione dodawanie tickera z nazwy plików\n\n\n\n")
    textbox.insert(END, " * v0.3\n")
    textbox.insert(END, "     - obsługa plików .txt\n")
    textbox.insert(END, "     - dodana kompatybilność konwersji .txt kwartalnej\n")
    textbox.insert(END, "     - dodana kompatybilność konwersji .txt dziennej\n")
    textbox.insert(END, "     - dodany nowy obiekt odpowiadajacy za stan aplikacji\n")
    textbox.insert(END, "     - zaimplementowany nowy skrypt decyzyjny odnośnie konwersji\n\n\n\n")
    textbox.insert(END, " * v0.2.3\n")
    textbox.insert(END, "     - poprawione komunikaty błędów\n")
    textbox.insert(END, "     - zmiana rozmieszczenia pól tekstowych\n\n\n\n")
    textbox.insert(END, " * v0.2.2\n")
    textbox.insert(END, "     - naprawione okienko wersji programu\n\n\n\n")
    textbox.insert(END, " * v0.2.1\n")
    textbox.insert(END, "     - dodana obsługa angielskich plików w konwersji kwartalnej\n")
    textbox.insert(END, "     - poprawki UI\n")
    textbox.insert(END, "     - version.txt - usuniete - stworzony pliku zapisu txt w wersjach\n\n\n\n")
    textbox.insert(END, " * v0.2\n")
    textbox.insert(END, "     - poprawki obsługi CSV\n")
    textbox.insert(END, "     - nowe formatowanie plików\n")
    textbox.insert(END, "     - dodanie formatowania PRN\n")
    textbox.insert(END, "     - obsługa zapisu do TXT\n")
    textbox.insert(END, "     - setup dla konwersji dziennej (OPENINT)\n")
    textbox.insert(END, "     - obsługa zapisu oddzielona od reszty programu\n\n\n\n")
    textbox.insert(END, " * v0.1\n")
    textbox.insert(END, "     - setup dla konwersji kwartalnej\n")
    textbox.insert(END, "     - obsługa ściezek i otwierania plikow\n")
    textbox.insert(END, "     - wsparcie WIN 7\n")
    textbox.insert(END, "     - pliki CSV\n\n\n\n")
    

    textbox.config(yscrollcommand=scrollbar.set)
    scrollbar.config(command=textbox.yview)
    root.mainloop()
